### ISSUE TITLE
[BUG] Nonlethal damage causes dying creature to stabilize

### ISSUE THREAD

**Issue by deerbuster** [deerbuster/SFRPG-public#1]
**Describe the bug (please make sure you are using the most recent live version.  If this is a bug on the test branch, please clearly indicate that it is.**
When the target of an attack is dying, if you apply nonlethal damage, it causes the target to add the stabilize condition.  It does not clear the dying condition

**To Reproduce**
1. Apply nonlethal damage to a PC with the Unconscious and Dying conditions applied
2. The Stable condition is applied to the PC target

**Expected behavior**
Nothing should change.  Stable condition should not be applied

**List any extensions you have loaded here:**
 - None

**Additional context**
This happens because the ActionDamageManager code applies the Stable condition to knock a target out instead of making them Dying when they have 0 HP.

**Comment by Samarex** [comment]
Fixed Revision 1.2.5

**Comment by Samarex** [comment]
Hiya didn't know you were still working

**Comment by Samarex** [comment]
If you are still doing things I need help.
Can we connect and talk about a big issue?

**Comment by deerbuster** [comment]
I just closed out this issue that you completed a long time ago
